[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
pxfm = {path = "../", features = []}

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }
libm = "0.2"

[[bench]]
name = "math"
harness = false
